services:
  mysql:
    image: mysql:8
    container_name: mysql-container-4EcommJEE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
volumes:
  mysql_data:
